version: '3'
services:
  web:
    image: gpica/microservice-division_web
    ports:
      - "3000:3000"

  quotient:
    image: gpica/microservice-division_quotient
    ports:
      - "3003:3000"

  dividend:
    image: gpica/microservice-division_dividend
    ports:
      - "3001:3000"

  divisor:
    image: gpica/microservice-division_divisor
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf


